2024-12-03 12:08:37,786 - __main__ - INFO - Starting ML pipeline...
2024-12-03 12:08:37,793 - root - INFO - Created directory: artifacts
2024-12-03 12:08:37,794 - root - INFO - Created directory: artifacts/ingested_data
2024-12-03 12:08:37,794 - root - INFO - Created directory: artifacts/transformed_data
2024-12-03 12:08:37,795 - root - INFO - Created directory: artifacts/models
2024-12-03 12:08:37,795 - root - INFO - Created directory: logs
2024-12-03 12:08:37,795 - __main__ - INFO - Step 1: Data Ingestion
2024-12-03 12:08:37,798 - __main__ - ERROR - Error in ML pipeline: [Errno 2] No such file or directory: './dataset/loan_approval_dataset.csv'
Traceback (most recent call last):
  File "C:\Users\mifth\OneDrive\Desktop\p\relaxy-ai-engineer-exam-question\src\main.py", line 67, in main
    X, y = data_ingestion.initiate_data_ingestion()
  File "C:\Users\mifth\OneDrive\Desktop\p\relaxy-ai-engineer-exam-question\src\data_ingestion.py", line 74, in initiate_data_ingestion
    raise e
  File "C:\Users\mifth\OneDrive\Desktop\p\relaxy-ai-engineer-exam-question\src\data_ingestion.py", line 47, in initiate_data_ingestion
    df = pd.read_csv(self.data_path)
  File "C:\Users\mifth\AppData\Local\Programs\Python\Python310\lib\site-packages\pandas\io\parsers\readers.py", line 912, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "C:\Users\mifth\AppData\Local\Programs\Python\Python310\lib\site-packages\pandas\io\parsers\readers.py", line 577, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "C:\Users\mifth\AppData\Local\Programs\Python\Python310\lib\site-packages\pandas\io\parsers\readers.py", line 1407, in __init__
    self._engine = self._make_engine(f, self.engine)
  File "C:\Users\mifth\AppData\Local\Programs\Python\Python310\lib\site-packages\pandas\io\parsers\readers.py", line 1661, in _make_engine
    self.handles = get_handle(
  File "C:\Users\mifth\AppData\Local\Programs\Python\Python310\lib\site-packages\pandas\io\common.py", line 859, in get_handle
    handle = open(
FileNotFoundError: [Errno 2] No such file or directory: './dataset/loan_approval_dataset.csv'
